export const TYPES = {
  BALANCE_LOADING_FAILED: "BALANCE_LOADING_FAILED",
  UPDATE_BALANCE: "UPDATE_BALANCE",
  LOADING_BALANCE: "LOADING_BALANCE",
  UDATE_CHAIN_DETAILS: "UDATE_CHAIN_DETAILS",
  UPDATE_CONNECTED_WALLET: "CONNECT_WALLET",
  WALLET_CONNECTED: "WALLET_CONNECTED",
  DISCONNECT_WALLET: "DISCONNECT_WALLET",
  WALLET_CONNECT_INITIALIZED: "WALLET_CONNECT_INITIALIZED",
  WEB3_JS_LOADED: "WEB3_JS_LOADED",
};
